mode: development

database:
  mongodb:
    name: "node-starter"
    default_collection: "default"
    uri: "mongodb://0.0.0.0:27017/node-starter"

cors:
  allow_origin: "*"
  allow_method: ["POST"]

rate_limiter:
  windowMs: 60000
  max: 100
  standardHeaders: true
  legacyHeaders: false