mode: production

application:
  logPath: "/var/embargo-logs/mng-api/"
  logOnFile: false
  logOnMongo: false
  logOnConsole: false

database:
  mongodb:
    name: "mng_api_production"
    default_collection: "default"
    uri: "mongodb://0.0.0.0:27017/mng_api_production"
  postgres:
    main:
      user: "//postgres"
      host: "//104.236.243.125"
      database: "//Embargo"
      password: "//developmentaccess"
      port: 005432
      idleTimeoutMillis: 005000
      connectionTimeoutMillis: 005000
    cloud:
      user: "//doadmin"
      host: "//db-postgresql-lon1-79473-do-user-1331563-0.b.db.ondigitalocean.com"
      database: "//mng_dev"
      password: "//qeh6gl9o3194swd9"
      port: 0025060
      idleTimeoutMillis: 005000
      connectionTimeoutMillis: 005000
      ssl:
        rejectUnauthorized: false

cors:
  allow_origin: "*"
  allow_method: ["POST"]

rate_limiter:
  windowMs: 60000
  max: 100
  standardHeaders: true
  legacyHeaders: false
